### ISSUE TITLE
Search for post

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/flovis-farmhouse#1]
Add the ability to search for a post by either it's MS ID or by a Stack Exchange URL

**Comment by AWegnerGitHub** [comment]
Are we sure this works? I've tried ten different URLs from posts made or edited in the last 15 minutes on SO, MSE and SFF and none of them show up in the search results.

**Comment by ArtOfCode-** [comment]
I tested it, but that's no guarantee it works on absolutely everything... What links have you tried?

**Comment by AWegnerGitHub** [comment]
I can't seem to replicate it now. I tried a new batch of new and newly edited and everything showed up.
