### ISSUE TITLE
What are the valid stages?

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/flovis-farmhouse#3]
After watching for a while, I've seen a few stages:

 - `received`
 - `bodyfetcher/enqueued` 
 - `bodyfetcher/api_response/not_spam`
 - `bodyfetcher/api_request`

I'm guessing there is also a `bodyfetcher/api_response/spam`.

What other stages are available and are there any "ERROR! LOOK AT ME!" stages that should be made visible? (If so, those should be a category in #2)

**Comment by ArtOfCode-** [comment]
For a full list, do a project wide search for `flovis.stage` in Smokey.

There is indeed a spam stage. There's also a bodyfetcher error and no content stage. There may be a couple others, but those are the main few.
